### ISSUE TITLE
💥 Project Vision 💥

### ISSUE THREAD

**Issue by Hona** [Hona/TempusHub2#1]
Login with Steam.

✨ Planned Features:

- Player Dashboard
  - Suggested Maps for Completion, or TT (based on other 'similar' players completion/tt which you should be similar to
  - Fun/Competitive maps suggested based on player ratings
  - Easy WR/Easy TT based on similar players (e.g. you have 95% match but don't have TT on something they have WR)
  - Friend Activity (steam friends?, site friends, site following?)
  - Progress Bars: Completion. TTs, WRs 
  - Map List Summary (bar goes from 0 (not complete) to 100% has WR). Sort by best/worst maps.
  - Favorited/Pinned maps
- Map View
  - Leaderboards/Points (EV, expected value, e.g. 50th percentile time vs points, or, similar players to you completion median time vs points)
  - Comments: Text, videos whatever. think maze tips, dumb setups, comments, how to cheat no tele. 
  - Community Data:
    - Images/Videos for the gallery
    - Rating (difficulty + fun - separately, verified using completion)
    - Tags (airpogo, hardpogo, speedshot etc. Should tags be community sourced?)
  - Auto Videos - any leaderboard run that was/is WR links to Tempus Records/Archive magically (no more searching youtube slowly)

- General Community sourced data:
  - peoples autoexec & config
  - scripts
  - custom textures/particles etc (all the hidden stuff that you have to ask to know about)
- Analytics: (we can do lots of cool stuff)
  - Rank history. Track all player ranks. Fastest growing histograph... one day animation after enough data.
  - Map WR history. animation also
  both these history things you see as youtube videos
  
  - What if (allow custom rank formula, map tiers?)
  - Time on Maps
  - Most run map/bonus
  - Most avoided
  - Most WRd
  - Biggest gap between run # 1-> # 2 and/or # 1- # 10
- Mobile App/PWA/Installed (even safari allows native push notifications lol)
  - WR notifications (allow all maps or only watched/favourited/followed maps or players)
  - Player on given Map
  - You lost a TT
  - You lost a WR
  - a # 2 or any top player/TT holder playing a map you have WR on
  - player WR dominance pie chart
- Querying
  - Capture historical data for permanent access. Allow querying ranges, specific dates & generally expose what data WAS.
- 💣 Jump as a Service
  - Tempus Records/Archive on demand: Serverless videos, e.g. request any run/player, WR zone completion whatever and get a video back. [Azure VM GPU](https://learn.microsoft.com/en-us/azure/virtual-machines/sizes-gpu)
    - Lets say you do a completion on a hard t6 for the first time, and want to uplaod it. Most people do it wrong or can't be bothered. Click a button then get a mp4 download using Tempus Records config/quality
    Spin up a VM then record video & dispose the VM. That way I can see how much $$$ im burning on cloud compute
  - Tempus TV on demand. (potentially many instances)
- STV Viewer
  - Custom upload? 
  - always on for WRs, map runs
  - Downlaod then display the chat logs to users. Any WRs etc.
- Clans
  - steam group? nickname suffix?
  - Clan leaderboards
  - Clan war. (set period of time, who gets the most points/WRs/TTs/Completion)
---

**Notes from Jumpers:**

Boshy: 
  - Important: Make it easy for new jumpers to get into it
  - Images/gallery for jump more than the 1 thumbnail

Luke: 
  - Content moderation

**Comment by MEGAWOP** [comment]
Seems good give now

**Comment by Hona** [comment]
TODO:

Rank changes (e.g. Hona just ranked up from 12 -> 11)

**Comment by Hona** [comment]
- Spotify recapped for each player (most played map, tts gained, wrs lost blah blah)
